version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run: 
          name: Init submodule
          command: git submodule update --init --recursive
      - run: 
          name: Import GPG keys
          command: ./build.sh -i
      - run: 
          name: Run Tests
          command: ./test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test