version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: ./test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test