version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: 
          name: Init submodule
          command: git submodule update --init --recursive
      - run: 
          name: Import GPG keys
          command: ./build.sh -i

      - setup_remote_docker:
          docker_layer_caching: false
          
      - run: 
          name: Run Tests
          command: ./test.sh

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - test